### ISSUE TITLE
Understand the table relationships with "_id"- kind of key attributes  

### ISSUE THREAD

**Issue by sofyalaski** [osc-em/converter-OSCEM-to-mmCIF#14]
# Description

In PDBx the data structure of choice is a table, where the category name represents a table name and the data ids are it's components. The are also attributes that connect each other by a certain attribute: that would usually contain a _category_name_.*name*_id. 
When provided to a certain sample, for instance a concrete instrument (by id) will be associated and shown correctly on OneDep. 

## Issue 
When ids are not provided at all, data is often not propagated to the fields. 

## Concerns
We don't really have that kind of relationship in OSC-EM. If we have many instances, it usually (?) does not affect the relationship with some other property. 
Is it then save to just add enumeration-like id to these properties to tie them up to other properties?

**Comment by sbliven** [comment]
I think it's usually ok. Looking through some EMDB entries it looks like ids can either be meaningful accessions (eg `_chem_comp.id`, `entry_id`) or sequential integers (eg `entity_id`). So I think as a default you can just use numbers.

**Comment by sofyalaski** [comment]
yes, I forgot to close this issue, as it's solved - I am adding some IDs for neccessary  data items
